from typing import Callable, Optional
from broker import Broker

class Emitter:
    uuid: str
    internal_resolve: Optional[Callable[[], None]]
    external_resolve: Optional[Callable[[], None]]

    def __init__(self, uuid: Optional[str] = ...) -> None: ...
    def register(self, broker: Broker) -> None: ...
    def emit(self) -> None: ...
    def resolve(self) -> None: ...
